version: "3.8"

services:
  memes_service:
    container_name: memes_service
    build:
      context: ./backend/memes_service
      dockerfile: Dockerfile
    volumes:
      - ./backend/memes_service:/backend/memes_service
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - minio-local

  db:
    image: postgres:16.2
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env
    ports:
      - "5433:5433"
    volumes:
      - pgdata:/var/lib/postgresql/data 

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    env_file:
      - .env
    ports:
      - "8888:80"
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
      - MINIO_DEFAULT_BUCKETS=${MINIO_DEFAULT_BUCKETS}
    env_file:
      - .env
    volumes:
      - minio-data:/var/lib/minio
    networks:
      - minio-local

networks:
  minio-local:
    driver: bridge

volumes:
  pgdata:
  pgadmin-data:
